#!/usr/bin/env node
/**
 * Version Name (semver, user-facing) + Build Number (monotonic, CI/build) manager.
 *
 * Source of truth: version.json
 * Runtime stamp:   electron/shared/version-stamp.js  (generated; gitignored optional)
 *
 * Commands:
 *   stamp                         Write stamp + sync package.json / project.yml
 *   bump-build                    Increment Build Number only (dev / CI / test)
 *   bump-version <patch|minor|major>  Bump Version Name (formal release only)
 *   release <patch|minor|major>   bump-version + bump-build + stamp
 *   print                         Print current version info as JSON
 *   set-build <n>                 Set Build Number explicitly (CI override)
 *
 * Env overrides (CI):
 *   VERSION_NAME          Force Version Name when stamping
 *   BUILD_NUMBER          Force Build Number when stamping / set-build
 *   GITHUB_SHA / GIT_COMMIT  Commit hash if not available via git
 */
'use strict';

const fs = require('node:fs');
const path = require('node:path');
const { execFileSync } = require('node:child_process');

const ROOT = path.resolve(__dirname, '..');
const VERSION_JSON = path.join(ROOT, 'version.json');
const STAMP_JS = path.join(ROOT, 'electron/shared/version-stamp.js');
const PACKAGE_JSON = path.join(ROOT, 'package.json');
const PROJECT_YML = path.join(ROOT, 'project.yml');

function readJson(file) {
  return JSON.parse(fs.readFileSync(file, 'utf8'));
}

function writeJson(file, data) {
  fs.writeFileSync(file, `${JSON.stringify(data, null, 2)}\n`, 'utf8');
}

function loadVersion() {
  const data = readJson(VERSION_JSON);
  const versionName = String(data.versionName || data.version || '0.0.0').replace(/^v/, '');
  const buildNumber = Number(data.buildNumber);
  if (!/^\d+\.\d+\.\d+$/.test(versionName)) {
    throw new Error(`Invalid versionName in version.json: ${versionName}`);
  }
  if (!Number.isInteger(buildNumber) || buildNumber < 1) {
    throw new Error(`Invalid buildNumber in version.json: ${data.buildNumber}`);
  }
  return { versionName, buildNumber };
}

function saveVersion({ versionName, buildNumber }) {
  writeJson(VERSION_JSON, { versionName, buildNumber });
}

function bumpSemver(versionName, level) {
  const parts = versionName.split('.').map((n) => Number(n));
  if (parts.length !== 3 || parts.some((n) => !Number.isInteger(n) || n < 0)) {
    throw new Error(`Cannot bump invalid semver: ${versionName}`);
  }
  let [major, minor, patch] = parts;
  if (level === 'major') {
    major += 1;
    minor = 0;
    patch = 0;
  } else if (level === 'minor') {
    minor += 1;
    patch = 0;
  } else if (level === 'patch') {
    patch += 1;
  } else {
    throw new Error(`Unknown bump level: ${level} (use patch|minor|major)`);
  }
  return `${major}.${minor}.${patch}`;
}

function gitCommit() {
  if (process.env.GITHUB_SHA) return String(process.env.GITHUB_SHA).slice(0, 12);
  if (process.env.GIT_COMMIT) return String(process.env.GIT_COMMIT).slice(0, 12);
  try {
    return execFileSync('git', ['rev-parse', '--short=12', 'HEAD'], {
      cwd: ROOT,
      encoding: 'utf8'
    }).trim();
  } catch {
    return 'unknown';
  }
}

function gitDirty() {
  try {
    const out = execFileSync('git', ['status', '--porcelain'], {
      cwd: ROOT,
      encoding: 'utf8'
    }).trim();
    return out.length > 0;
  } catch {
    return false;
  }
}

function syncPackageJson(versionName, buildNumber) {
  const pkg = readJson(PACKAGE_JSON);
  pkg.version = versionName;
  pkg.build = pkg.build || {};
  // electron-builder: CFBundleShortVersionString ← version, CFBundleVersion ← buildVersion
  pkg.build.buildVersion = String(buildNumber);
  writeJson(PACKAGE_JSON, pkg);
}

function syncProjectYml(versionName, buildNumber) {
  if (!fs.existsSync(PROJECT_YML)) return;
  let yml = fs.readFileSync(PROJECT_YML, 'utf8');
  yml = yml.replace(
    /MARKETING_VERSION:\s*"[^"]*"/,
    `MARKETING_VERSION: "${versionName}"`
  );
  yml = yml.replace(
    /CURRENT_PROJECT_VERSION:\s*"[^"]*"/,
    `CURRENT_PROJECT_VERSION: "${buildNumber}"`
  );
  fs.writeFileSync(PROJECT_YML, yml, 'utf8');
}

function writeStamp(meta) {
  const {
    versionName,
    buildNumber,
    gitCommit: commit,
    builtAt,
    channel
  } = meta;
  const display = `Version ${versionName} (Build ${buildNumber})`;
  const body = `/**
 * AUTO-GENERATED by scripts/version.js — do not edit by hand.
 * Run: node scripts/version.js stamp
 */
(function (root, factory) {
  const stamp = factory();
  if (typeof module === 'object' && module.exports) {
    module.exports = stamp;
  }
  root.TtpVersion = stamp;
})(typeof globalThis !== 'undefined' ? globalThis : this, function () {
  return {
    versionName: ${JSON.stringify(versionName)},
    buildNumber: ${JSON.stringify(buildNumber)},
    gitCommit: ${JSON.stringify(commit)},
    builtAt: ${JSON.stringify(builtAt)},
    channel: ${JSON.stringify(channel)},
    display: ${JSON.stringify(display)}
  };
});
`;
  fs.mkdirSync(path.dirname(STAMP_JS), { recursive: true });
  fs.writeFileSync(STAMP_JS, body, 'utf8');
}

function resolveMeta(base) {
  const versionName = process.env.VERSION_NAME
    ? String(process.env.VERSION_NAME).replace(/^v/, '')
    : base.versionName;
  const buildNumber = process.env.BUILD_NUMBER
    ? Number(process.env.BUILD_NUMBER)
    : base.buildNumber;
  if (!Number.isInteger(buildNumber) || buildNumber < 1) {
    throw new Error(`Invalid BUILD_NUMBER: ${process.env.BUILD_NUMBER}`);
  }
  const channel = process.env.RELEASE_CHANNEL
    || (process.env.CI ? 'ci' : 'dev');
  return {
    versionName,
    buildNumber,
    gitCommit: gitCommit(),
    builtAt: new Date().toISOString(),
    channel,
    dirty: gitDirty(),
    display: `Version ${versionName} (Build ${buildNumber})`
  };
}

function stamp() {
  const base = loadVersion();
  const meta = resolveMeta(base);
  // Persist env overrides back into version.json when CI injects them
  if (process.env.VERSION_NAME || process.env.BUILD_NUMBER) {
    saveVersion({ versionName: meta.versionName, buildNumber: meta.buildNumber });
  }
  writeStamp(meta);
  syncPackageJson(meta.versionName, meta.buildNumber);
  syncProjectYml(meta.versionName, meta.buildNumber);
  console.log(
    `[version] stamped ${meta.display} commit=${meta.gitCommit} channel=${meta.channel}`
  );
  return meta;
}

function bumpBuild() {
  const current = loadVersion();
  const next = {
    versionName: current.versionName,
    buildNumber: current.buildNumber + 1
  };
  if (process.env.BUILD_NUMBER) {
    next.buildNumber = Number(process.env.BUILD_NUMBER);
  }
  saveVersion(next);
  console.log(
    `[version] build ${current.buildNumber} → ${next.buildNumber} (name ${next.versionName})`
  );
  return next;
}

function bumpVersion(level) {
  const current = loadVersion();
  const nextName = bumpSemver(current.versionName, level);
  const next = { versionName: nextName, buildNumber: current.buildNumber };
  saveVersion(next);
  console.log(
    `[version] versionName ${current.versionName} → ${nextName} (${level})`
  );
  return next;
}

function setBuild(n) {
  const current = loadVersion();
  const buildNumber = Number(n);
  if (!Number.isInteger(buildNumber) || buildNumber < 1) {
    throw new Error(`Invalid build number: ${n}`);
  }
  const next = { versionName: current.versionName, buildNumber };
  saveVersion(next);
  console.log(`[version] buildNumber set to ${buildNumber}`);
  return next;
}

function release(level) {
  bumpVersion(level);
  bumpBuild();
  return stamp();
}

function print() {
  const base = loadVersion();
  const meta = resolveMeta(base);
  const out = {
    versionName: meta.versionName,
    buildNumber: meta.buildNumber,
    display: `Version ${meta.versionName} (Build ${meta.buildNumber})`,
    gitCommit: meta.gitCommit,
    channel: meta.channel,
    dirty: meta.dirty
  };
  console.log(JSON.stringify(out, null, 2));
  return out;
}

function usage() {
  console.log(`Usage:
  node scripts/version.js stamp
  node scripts/version.js bump-build
  node scripts/version.js bump-version <patch|minor|major>
  node scripts/version.js release <patch|minor|major>
  node scripts/version.js set-build <n>
  node scripts/version.js print
`);
}

function main(argv) {
  const [cmd, arg] = argv;
  switch (cmd) {
    case 'stamp':
      stamp();
      break;
    case 'bump-build':
      bumpBuild();
      stamp();
      break;
    case 'bump-version':
      if (!arg) throw new Error('bump-version requires patch|minor|major');
      bumpVersion(arg);
      stamp();
      break;
    case 'release':
      if (!arg) throw new Error('release requires patch|minor|major');
      release(arg);
      break;
    case 'set-build':
      if (!arg) throw new Error('set-build requires a number');
      setBuild(arg);
      stamp();
      break;
    case 'print':
      print();
      break;
    case undefined:
    case 'help':
    case '-h':
    case '--help':
      usage();
      break;
    default:
      usage();
      throw new Error(`Unknown command: ${cmd}`);
  }
}

try {
  main(process.argv.slice(2));
} catch (error) {
  console.error(`[version] ${error.message || error}`);
  process.exit(1);
}
