/**
 * AUTO-GENERATED by scripts/version.js — do not edit by hand.
 * Run: node scripts/version.js stamp
 */
(function (root, factory) {
  const stamp = factory();
  if (typeof module === 'object' && module.exports) {
    module.exports = stamp;
  }
  root.TtpVersion = stamp;
})(typeof globalThis !== 'undefined' ? globalThis : this, function () {
  return {
    versionName: "0.1.0",
    buildNumber: 1,
    gitCommit: "cc13d76d454d",
    builtAt: "2026-07-15T07:01:45.212Z",
    channel: "dev",
    display: "Version 0.1.0 (Build 1)"
  };
});
